# Generated by Django 5.2.1 on 2025-05-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('total_vagas', models.IntegerField()),
                ('vagas_disponiveis', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myApp.cliente')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
            bases=('myApp.cliente',),
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('estacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.estacionamento')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField()),
                ('codigo', models.CharField(max_length=20)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.cliente')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Contem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.estacionamento')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.estacionamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.administrador')),
            ],
        ),
    ]
