# Generated by Django 5.2.1 on 2025-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_vaga_disponivel_vaga_id_user_alter_vaga_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
