# Generated by Django 5.2.1 on 2025-06-16 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_vaga_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_entrada", models.DateTimeField(auto_now_add=True)),
                ("hora_saida", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_vagas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_ocupacao",
                        to="myApp.vaga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Reserva",
                "verbose_name_plural": "Histórico de Reservas",
                "ordering": ["-hora_entrada"],
            },
        ),
    ]
