# Generated by Django 5.2.1 on 2025-06-16 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_historicoreserva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoContadorEstacionamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_paradas", models.IntegerField(default=0)),
                (
                    "estacionamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contagem_usuarios",
                        to="myApp.estacionamento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contagem_estacionamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contador de Paradas no Estacionamento",
                "verbose_name_plural": "Contadores de Paradas nos Estacionamentos",
                "unique_together": {("user", "estacionamento")},
            },
        ),
        migrations.DeleteModel(
            name="HistoricoReserva",
        ),
    ]
