# Generated by Django 5.2.1 on 2025-06-16 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_historicocontadorestacionamento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricoContadorEstacionamento",
            new_name="Historico",
        ),
    ]
