# Generated by Django 5.2.1 on 2025-06-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_historicocontadorestacionamento_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='dias_funcionamento',
            field=models.CharField(default='Segunda a Sexta', max_length=255),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='horario_atendimento',
            field=models.CharField(default='08:00 - 18:00', max_length=100),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='modo_cobranca',
            field=models.CharField(default='Por hora', max_length=100),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='tipo',
            field=models.CharField(default='Geral', max_length=100),
        ),
    ]
